config/routes.rb
Rails.application.routes.draw do
  get 'mongoid/index'
  get 'welcome/index'
  get 'map/index'
  get 'mongo/index'
  # get 'mongoid/index'

  resources :bornes,:mongoid, :mongo
  root 'welcome#index'

end

app/controllers/mongoid_controller.rb
require 'net/http'

class MongoidController < ApplicationController
  before_action :set_borneelec, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => :create

    # GET /mongoid
    # GET /mongoid.json
  def index
    @bornelecs = Borneelec.all
    @bornelecs.each  {  |doc|
      puts doc['adresse']
      puts doc['ville']
      puts doc['codepostal']
      puts doc['latitude']
      puts doc['longitude']
      puts doc['tarif']
      puts "ID: "+doc['id']
      puts "_ID "+doc['_id']
    }
  end

    # GET /mongoid/1
    # GET /mongoid/1.json
  def show
    @bornelec=Borneelec.find(params[:id])
  end
  # GET /mongoid/1
  # GET /mongoid/1.json
  def edit
    @bornelec=Borneelec.find(params[:id])
  end
    # GET /mongoid/new
  def new
    @bornelec = Borneelec.new
  end


    # POST /mongoid
    # POST /mongoid.json
  def create
    # @bornelec = Borneelec.new(borneelec_params)
    #
    # respond_to do |format|
    #   if @bornelec.save
    #     format.html { redirect_to @bornelec, notice: 'bornelec was successfully created.' }
    #     format.json { render :show, status: :created, location: @bornelec }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @bornelec.errors, status: :unprocessable_entity }
    #   end
    # end
    #

    @bornelec = Borneelec.new(borneelec_params)

        if @bornelec.save
            redirect_to action: "index"
        else
            render 'new'
        end
  end

    # PATCH/PUT /mongoid/1
    # PATCH/PUT /mongoid/1.json
  def update
    # respond_to do |format|
    #
    #   if @bornelec.update(borneelec_params)
    #     puts @bornelec['name']
    #     format.html { redirect_to @bornelec, notice: 'bornelec was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @bornelec }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @bornelec.errors, status: :unprocessable_entity }
    #   end
    # end
  @bornelec=Borneelec.find(params[:id])
  @bornelec.update(borneelec_params)
    redirect_to action: "index"


  end

    # DELETE /mongoid/1
    # DELETE /mongoid/1.json
  def destroy
    # @bornelec.destroy
    # respond_to do |format|
    #   format.html { redirect_to mongoid_url, notice: 'bornelec was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    #
    @bornelec=Borneelec.find(params[:id])
    @bornelec.destroy
    redirect_to action: "index"

  end

  private

    # Use callbacks to share common setup or constraints between actions.
  def set_borneelec
    @bornelec = Borneelec.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def borneelec_params
    params.require(:borneelec).permit(:id, :name, :adresse, :ville,:codepostal,:latitude,:longitude,:tarif)
  end
  end

app/helpers/mongoid_helper.rb
module MongoidHelper
end

app/views/mongoid/edit.html.erb
<h1>Modifier la borne <%= @bornelec.name %></h1>

<%= form_for @bornelec, url: mongoid_path(@bornelec), method: :put do |f| %>
  <% if @bornelec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bornelec.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% @bornelec.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :adresse %><br>
    <%= f.text_field :adresse , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :codepostal %><br>
    <%= f.text_field :codepostal, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :ville %><br>
    <%= f.text_field :ville, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :tarif %><br>
    <%= f.text_field :tarif, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <!--    <button type="submit" class="btn btn-prymary">fd</button>-->
  </div>


<%= link_to 'Back', mongoid_index_url %>

<% end %>

app/views/mongoid/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Liste des Bornes</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">adresse</th>
      <th scope="col">Ville</th>
         <th scope="col">Code Postal</th>
         <th scope="col">Latitude</th>
         <th scope="col">Longitude</th>
         <th scope="col">Tarif</th>

    </tr>
  </thead>
        <% Borneelec.each do |borneelec| %>

  <tbody>
 <tr>
    <td><%= borneelec.name %></td>
    <td><%= borneelec.adresse %></td>
    <td><%= borneelec.ville %></td>
    <td><%= borneelec.codepostal %></td>
    <td><%= borneelec.latitude %></td>
    <td><%= borneelec.longitude %></td>
    <td><%= borneelec.tarif %></td>

<!--      <td><%#= link_to 'Détails', mongoid_path(borneelec.id),:class => "btn btn-primary"  %></td>-->
      &nbsp;
       <td><%= link_to 'Modifier', edit_mongoid_path(borneelec) %></td>
      &nbsp;
      <td><%= button_to 'Supprimer', mongoid_path(borneelec.id), method: :delete , class: "btn btn-primary"%></td>
    </div>
  <% end %>
</div>
<br>

<%= link_to 'New Borne' , new_mongoid_path %>

app/views/mongoid/new.html.erb
<h1>Nouvelle Borne</h1>

<%#= render 'form' %>
<%= form_for @bornelec, url: { action: "create" }, method: :post do |f| %>
  <% if @bornelec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bornelec.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% @bornelec.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :adresse %><br>
    <%= f.text_field :adresse , class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :codepostal %><br>
    <%= f.text_field :codepostal, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :ville %><br>
    <%= f.text_field :ville, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :tarif %><br>
    <%= f.text_field :tarif, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <!--    <button type="submit" class="btn btn-prymary">fd</button>-->
  </div>
<% end %>

<%= link_to 'Back', mongoid_index_url %>

app/views/mongoid/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name :</strong>
  <%= @bornelec.name %>
</p>
<p>
  <strong>Adresse :</strong>
  <%= @bornelec.adresse %>
</p>

<p>
  <strong>Code Postal:</strong>
  <%= @bornelec.codepostal %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @bornelec.ville %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @bornelec.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @bornelec.longitude %>
</p>
<p>
  <strong>Tarif:</strong>
  <%= @bornelec.tarif %>
</p>

<%= link_to 'Edit', edit_mongoid_path(@bornelec) %> |

<%= link_to 'Revenir a la liste des bornes', 'index' %>