config/routes.rb
Rails.application.routes.draw do
  get 'mongoid/index'
  get 'welcome/index'
  get 'map/index'
  get 'mongo/index'
  # get 'mongoid/index'

  resources :bornes,:mongoid, :mongo
  root 'welcome#index'

end

app/models/borne.rb
class Borne < ApplicationRecord
  mount_uploader :picture, PictureUploader

  def to_s
    self.id
  end
end

app/controllers/bornes_controller.rb
class BornesController < ApplicationController

  before_action :set_borne, only: [:show, :edit, :update, :destroy]

  # GET /bornes
  # GET /bornes.json
  def index
    @bornes = Borne.all
  end

  # GET /bornes/1
  # GET /bornes/1.json
  def show
    sql = "Select *    FROM bornes where id ="+@borne.id.to_s

    @records_array = ActiveRecord::Base.connection.exec_query(sql)




    @result_array = ['something', 'second_something',@borne.id ]
  end

  # GET /bornes/new
  def new
    @borne = Borne.new
  end

  # GET /bornes/1/edit
  def edit

    sql = "Select * FROM bornes   where id ="+@borne.id.to_s

    @records_array = ActiveRecord::Base.connection.exec_query(sql)

    @result_array = ['something', 'second_something',@borne.id ]

  end

  # POST /bornes
  # POST /bornes.json
  def create
    @borne = Borne.new(borne_params)
    p @borne.to_s
    p @borne.id

    respond_to do |format|
      if @borne.save
        format.html { redirect_to @borne, notice: 'borne was successfully created.' }
        format.json { render :show, status: :created, location: @borne }
      else
        format.html { render :new }
        format.json { render json: @borne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bornes/1
  # PATCH/PUT /bornes/1.json
  def update
    respond_to do |format|
      if @borne.update(borne_params)
        format.html { redirect_to @borne, notice: 'borne was successfully updated.' }
        format.json { render :show, status: :ok, location: @borne }
      else
        format.html { render :edit }
        format.json { render json: @borne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bornes/1
  # DELETE /bornes/1.json
  def destroy
    @borne.destroy
    respond_to do |format|
      format.html { redirect_to bornes_url, notice: 'borne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_borne
    @borne = Borne.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def borne_params
    params.require(:borne).permit(:Adresse, :Ville, :CodePostal , :Latitude, :Longitude, :Tarif)
  end
end

app/helpers/bornes_helper.rb
module BornesHelper
end

app/views/bornes/_form.html.erb
  <%= form_for @borne, url: borne_path(@borne), method: :put do |form| %>

    <% if borne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(borne.errors.count, "error") %> prohibited this borne from being saved:</h2>

      <ul>
      <% borne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <p>Form begin dans form html</p>
  <p><h1> ingedients</h1>
  <%= @result_array %>


  <h1> ingedients</h1>
  <%= @records_array %> <br>

  <% @records_array.each do |val| %>
    <% val.each do |k, v| %>
      <%= "#{v}" %>
    <% end %>
  <% end %>
  <div class="field">
    <%= form.label :Adresse %>
    <%= form.text_field :Adresse %>
  </div>

  <div class="field">
    <%= form.label :Tarif %>
    <%= form.number_field :Tarif , :step => 0.5%>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

  <div class="row">



    <div class="col-lg-4 col-md-4 ">

        <div class="card-body text-center">
          <h4 class="card-title"><%= @borne.Adresse %></h4>
          <p class="card-text"><%= @borne.Tarif %>   euros </p>
          <%= link_to 'bornes list', bornes_path ,:class => "btn btn-primary" %>
        </div>

      </div>
      <br>
    </div>

    <div class="col-lg-4 col-md-4 ">

        <div class="card-body text-center">
          <h4 class="card-title"><%= @borne.Adresse %></h4>
          <p class="card-text"><%= @borne.Tarif %>   euros </p>
          <%= link_to 'bornes list', bornes_path ,:class => "btn btn-primary" %>
        </div>

      </div>
      <br>
    </div>
    <div class="col-lg-4 col-md-4 ">
      <div class="card  ">
        <ul class="list-group">
        <% @records_array.each do |val| %>

              <% val.each do |k, v| %>
              <li class="list-group-item"><%= "#{k} :  #{v}" %></li>
              <% end %>
            <li class="list-group-item active"> </li>
        <% end %>
        </ul>

        </div>

      </div>
      <br>
    </div>

  </div>

<% end %>

app/views/bornes/_form1.html.erb
  <%= form_for @borne, url: { action: "create" }, method: :post do |form| %>

    <% if @borne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(borne.errors.count, "error") %> prohibited this borne from being saved:</h2>

      <ul>
      <% borne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <p>Form begin dans form html</p>

  <div class="field">
    <%= form.label :Adresse %>
    <%= form.text_field :Adresse %>
    <br/>
    <%= form.label :Ville %>
    <%= form.text_field :Ville %>
    <br/>
    <%= form.label :CodePostal %>
    <%= form.text_field :CodePostal %>
    <br/>
    <%= form.label :Latitude %>
    <%= form.text_field :Latitude %>
    <br/>
    <%= form.label :Longitude %>
    <%= form.text_field :Longitude %>
    <br/>

  </div>

  <div class="field">
    <%= form.label :Tarif %>
    <%= form.number_field :Tarif , :step => 0.5%>
  </div>

<!--  <div class="field">-->
    <%#= form.label :picture %>
    <%#= form.file_field  :picture %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>

<!--  <div class="row">-->



<!--    <div class="col-lg-4 col-md-4 ">-->
<!--      <div class="card  ">-->
        <%# if  File.file?( Rails.root.join("app/assets/images/#{@borne.id}.jpg")) %>
        <%#= image_tag ("/assets/#{@borne.id}.jpg")  , class: " img1 img-responsive card-img-top "%>
        <%# else %>
          <%#= image_tag ("/assets/99.jpg")  , class: " img1 img-responsive card-img-top "%>

        <%# end %>
<!--        <div class="card-body text-center">-->
<!--          <h4 class="card-title"><%#= @borne.Designpizz %></h4>-->
<!--          <p class="card-text"><%#= @borne.Tarifpizz %>   euros </p>-->
<!--          <p>Numéro image  : <%#= @borne.id %></p>-->
<!--          <p>Chemin image  :<%#=  "/assets/#{@borne.id}.jpg" %></p>-->
<!--          <p><%#= Rails.root.join("app/assets/images") %></p>-->
          <%#= link_to 'bornes list', bornes_path ,:class => "btn btn-primary" %>
<!--        </div>-->

<!--      </div>-->
<!--      <br>-->
<!--    </div>-->

<!--    <div class="col-lg-4 col-md-4 ">-->
<!--      <div class="card  ">-->
          <%# if @borne.picture.present? %>
                <%#= image_tag (@borne.picture_url) , class: " img1 img-responsive card-img-top" %>
          <%# else %>
            <%#= image_tag ("/assets/99.jpg")  , class: " img1 img-responsive card-img-top "%>

        <%# end %>

<!--        <div class="card-body text-center">-->
<!--          <h4 class="card-title"><%#= @borne.Designpizz %></h4>-->
<!--          <p class="card-text"><%#= @borne.Tarifpizz %>   euros </p>-->
<!--          <p>Nom image  : <%#= @borne.picture_url %></p>-->
<!--          <p>Chemin image  : <%#= @borne.picture %></p>-->

          <%#= link_to 'bornes list', bornes_path ,:class => "btn btn-primary" %>
<!--        </div>-->

<!--      </div>-->
<!--      <br>-->
<!--    </div>-->


<!--  </div>-->

<% end %>

app/views/bornes/edit.html.erb
<h1>Editing borne</h1>

<%= render 'form', borne: @borne  %>



<%= link_to 'Show', @borne %> |
<%= link_to 'Back', bornes_path %>

app/views/bornes/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Liste des Bornes</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">adresse</th>
      <th scope="col">Ville</th>
         <th scope="col">Code Postal</th>
         <th scope="col">Latitude</th>
         <th scope="col">Longitude</th>
         <th scope="col">Tarif</th>

    </tr>
  </thead>

  <tbody>


    <% @bornes.each do |borne| %>
     <tr>
        <td><%= borne.Adresse %></td>
        <td><%= borne.Ville %></td>
        <td><%= borne.CodePostal %></td>
        <td><%= borne.Latitude %></td>
        <td><%= borne.Longitude %></td>
        <td><%= borne.Tarif %></td>




         <td> <%= link_to 'Show', borne , :class => "btn btn-primary" %>
          <%= link_to 'Edit', edit_borne_path(borne) , :class => "btn btn-primary" %>
          <%= link_to 'Destroy', borne, method: :delete, data: {confirm: 'Are you sure?'} , :class => "btn btn-primary" %>

        </div>
</td>
      </div>
      <br>
      </div>

    <% end %>


</div>
<br>

<%= link_to 'New borne', new_borne_path %>

app/views/bornes/index.htmlcopie.erb
<p id="notice"><%= notice %></p>

<h1>bornes</h1>

<table>
  <thead>
    <tr>
      <th>Designpizz</th>
      <th>Tarifpizz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bornes.each do |borne| %>
      <tr>
        <td><%= borne.Designpizz %></td>
        <td><%= borne.Tarifpizz %></td>
        <td><%= link_to 'Show', borne %></td>
        <td><%= link_to 'Edit', edit_borne_path(borne) %></td>
        <td><%= link_to 'Destroy', borne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New borne', new_borne_path %>

app/views/bornes/new.html.erb
<h1>Nouvelle Borne</h1>

<%= render 'form1', borne: @bornes %>

<%= link_to 'Back', bornes_path %>

app/views/bornes/show.html.erb
<p id="notice"><%= notice %></p>

<p><h1> ingedients</h1>
<%=@result_array  %>


<h1> ingedients</h1>
<%=@records_array  %> <br>

<% @records_array.each   do |val| %>
 <% val.each do |k,v| %>
    <%=  "#{k} #{v}" %> <br>
         <% end %>
<% end %>
<br>
  <strong>Designpizz:</strong>
  <%= @borne.Adresse %>

</p>

<p>
  <strong>Tarifpizz:</strong>
  <%= @borne.Ville %>
</p>

<!--<p>-->
<!--  <strong>Picture:</strong>-->
  <%#= @borne.picture %>
<!--</p>-->

<%= link_to 'Edit', edit_borne_path(@borne) %> |
<%= link_to 'Back', bornes_path %>



<div class="row">



    <div class="col-lg-4 col-md-4 ">
      <div class="card  ">
        <%= image_tag ("/assets/#{@borne.id}.jpg"), class: " img1 img-responsive card-img-top "%>
        <div class="card-body text-center">
          <h4 class="card-title"><%= @borne.Adresse %></h4>
          <p class="card-text"><%= @borne.Ville %>   euros </p>

          <%= link_to 'Edit', edit_borne_path(@borne) ,:class => "btn btn-primary" %>
          <%= link_to 'bornes list', bornes_path ,:class => "btn btn-primary" %>
        </div>

      </div>
      <br>
    </div>
  <div class="col-lg-4 col-md-4 ">
    <div class="card  ">

      <div class="card-body text-center">
        <h4 class="card-title"><%= @borne.Adresse %></h4>
        <p class="card-text"><%= @borne.Ville %>   euros </p>
        <%= link_to 'bornes list', bornes_path ,:class => "btn btn-primary" %>
      </div>

    </div>
    <br>
  </div>

  <div class="col-lg-4 col-md-4 ">
    <div class="card  ">


      <div class="card-body text-center">
        <h4 class="card-title"><%= @borne.Adresse %></h4>
        <p class="card-text"><%= @borne.Ville %>   euros </p>
        <%= link_to 'bornes list', bornes_path ,:class => "btn btn-primary" %>
      </div>

    </div>
    <br>
  </div>



</div>